version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Jakarta"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Jakarta"
